dist: precise

language: node_js
node_js:
  - "node"
  - 6
  - 7
  - 8

install: true
before_script:
  - npm i -g yarn
  - yarn global add npm-check-updates

script:
  - export ROOT=$PWD
  - >
    for path in \
      flex \
      06-patterns/07-publish-subscriber \
      06-patterns/06-observer \
      06-patterns/05-constructor \
      06-patterns/04-decorator \
      06-patterns/03-facade \
      06-patterns/02-factory \
      06-patterns/01-strategy \
      05-mustache-jquery-cycle-bootswatch \
      04-vanilla-js-jquery \
      03-vanilla-js-jsonp \
      02-vanilla-js-remote-json \
      01-init-vanilla-js
    do

      export TARGET="$ROOT/$path"
      cd $TARGET

      yarn -i
      yarn predeploy
      yarn postdeploy
      if [ -f npm-debug.log ]; then cat npm-debug.log; fi

      ncu
      ncu -u
      yarn -i
      yarn upgrade
      if [ -f npm-debug.log ]; then cat npm-debug.log; fi

    done;

cache:
  directories:
    - node_modules
    - $HOME/.npm
